local_costmap:
  global_frame: odom  # Đổi từ map sang odom
  robot_base_frame: base_link
  update_frequency: 5.0
  publish_frequency: 2.0
  transform_tolerance: 1.0  # Tăng giá trị
  static_map: false
  rolling_window: true
  width: 4.0
  height: 4.0
  resolution: 0.05